name: Greeting on variable day

on:
  push

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: self-hosted
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "${{env.Greeting}} ${{env.First_Name}}. Today is ${{env.DAY_OF_WEEK}}!"
        env:
          First_Name: Mona
      - name : "Actor"
        run: echo "Actor is ${{env.GITHUB_ACTOR}}"
      
