name: Node.js CI

on:
  push

jobs:
  build:

    runs-on: self-hosted


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: sum.js
