name: Node.js CI

on:
  push

jobs:
  build:

    runs-on: self-hosted


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - uses: actions/upload-artifact@v2
        with:
          name: jeff-artificats
          path: node_modules/@babel/code-frame

      - uses: actions/download-artifact@v2
        with:
          name: jeff-artificats
          path: path/to/artifact
          
      - name: Display structure of downloaded files
        run: dir
        working-directory: path/to/artifact
